### ISSUE TITLE
Пауза

### ISSUE THREAD

**Issue by krishnacenter** [itwillwork/youtube-stay-focused#1]
Спасибо за замечательный плагин о котором я долго мечтал. Единственная проблема, при нажатии на паузу в видео ролике, плагин перестаёт работать. Хотелось бы чтобы он работал всегда, либо иметь настройку чтобы этим управлять.

**Comment by krishnacenter** [comment]
Попробовал с другим видео и проблема исчезла. Видимо что-то с кешем было и нужно было перезагрузить вкладку.

**Comment by krishnacenter** [comment]
А нет, снова вернулась, сброс кеша не помог. Некоторые видео ОК, а некоторые Не ок, вот с этим видео при паузе или при прокрутке вниз плагин перестаёт работать: https://www.youtube.com/watch?v=FK_FSOCC3ss гляньте пожалуйста

**Comment by Nikitozz13** [comment]
Подтверждаю баг с этим видео выше. Порой при загрузке просто нет фильтров, порой они появляются, но с прокруткой исчезают

**Comment by itwillwork** [comment]
починено в версии 1.3
