### ISSUE TITLE
Зачем скрывать всё видео?

### ISSUE THREAD

**Issue by krishnacenter** [itwillwork/youtube-stay-focused#3]
Зачем скрывать всё видео: 
- в трендах, 
- на главной,
- в подписках?

Если не нужны будут эти видео, мы просто не перейдём на эти категории. Данная настройка не понятна. 

Вот если бы можно было бы помечать просмотренные видео чтобы они не показывались, либо блокировать самому видео в трендах, то было бы интересно попробовать.

**Comment by itwillwork** [comment]
Моя ошибка была в том что сделал их по умолчанию включенными (сам такой настройкой пользуюсь), сделал в версии 1.4 выключенными по умолчанию.

> Вот если бы можно было бы помечать просмотренные видео чтобы они не показывались, либо блокировать самому видео в трендах, то было бы интересно попробовать.

Думаю все-таки любое расширение должно хорошо решать только одну проблему, поэтому думаю такого функционала не будет
